name: Auto Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        uses: actions/checkout@v6

      - name: download-spreadsheet
        run: python utils/download_spreadsheet.py

      - name: package-data
        run: |
          mkdir data
          cp -r assets data/
          cp "iRNHO's Spreadsheet.xlsx" main.py data/
          cd data
          zip -r ../data.zip .

      - name: create-release
        uses: softprops/action-gh-release@v2
        with:
          files: data.zip
          body: "Auto Release (${{ github.ref_name }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
